package pantryAppPackage.backend;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;

public class ShoppingList {
    private final Path shoppingListFile = Paths.get("src/main/resources/shopping_lists.txt");

    private User listOwner;
    private int list_id;
    private String Date_Created;

    private ArrayList<Object[]> items_list = new ArrayList<>(); // actual list of items in the shopping list
    private final ArrayList<ShoppingList> all_shopping_lists = new ArrayList<>(); // Declare an ArrayList of all shopping lists.

    public ShoppingList() {}

    public ShoppingList(User owner, int id, String dateCreated) {
        listOwner = owner;
        list_id = id; // temporarily set by input, will be changed to be autogenerated
        Date_Created = dateCreated;

        all_shopping_lists.add(this); // Add each shopping list created
    }

    public void addItem(Item item, int quantity, String unit) {
        // check
        if (item.getItemQuantity() > quantity) {
            // update
            items_list.add(new Object[] {item, quantity});
        }
        // warning
        else {throw new IllegalStateException("The quantity requested exceeds the quantity in storage");}
    }


    public void removeItem(Item item, int quantity, String unit) {
        // check
        if (item.getItemQuantity() > quantity) {
            // removeIf iterates through the list
            // for each Object[] in list, checks if first element (i[0]) equals the item
            items_list.removeIf(i -> i[0].equals(item));
        }
        // warning
        else {throw new IllegalStateException("The quantity requested exceeds the quantity in storage");}
    }


    public void markPurchased() { // restocks purchased items automatically
        // Goes through shopping list and restocks every item with quantity bought
        for (Object[] item_details : items_list) {
            Item item = (Item) item_details[0];
            int quantity = (int) item_details[1];

            item.setItemQuantity(item.getItemQuantity() + quantity); // adds quantity bought

            items_list = new ArrayList<>(); // refresh shopping list
        }
    }


    public void saveList() {
        try (BufferedWriter bw = Files.newBufferedWriter(shoppingListFile)) { // Automatically closes bw
            for (ShoppingList L : all_shopping_lists) {
                bw.write(String.join("|", L.getListOwner().getName(), Integer.toString(L.getList_id()), L.getDate_Created(), L.getItems_List().toString() ));
                bw.newLine();
            }
        } catch (IOException e) {
            throw new RuntimeException("Failed to save shopping_lists.txt", e);
        }
    } // reuse code from AuthServices to update txt database




    // Setters
    public void setList_id(int list_id) {
        this.list_id = list_id;
    }

    // Getters
    public User getListOwner() {
        return listOwner;
    }
    public int getList_id() {
        return list_id;
    }
    public String getDate_Created() {
        return Date_Created;
    }
    public ArrayList<Object[]> getItems_List() {
        return items_list;
    }
}
