package pantryAppPackage;

import java.util.List;
import java.util.ArrayList;
import java.nio.file.Path;           
import java.nio.file.Paths;      
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class PantryDashboard implements DashboardHelpers {

    private User user; // dashboard belongs to one user
    private List<Item> items; // list of item objects
    private List<ShoppingList> shoppingLists; // list of shopping lists
    private final Path itemsFile = Paths.get("src/main/resources/items.txt");
    String currentDate= LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy/MM/dd"));

    // setters and getters
    public User getUser() { 
      return user; 
    }
    public List<Item> getItems() { 
      return items;
    }
    public void setItems(List<Item> items) { 
      this.items = items;
    }
    public List<ShoppingList> getShoppingLists() {
      return shoppingLists; 
    }
    public void setShoppingLists(List<ShoppingList> shoppingLists) { 
      this.shoppingLists = shoppingLists;
    }

    // default constructor
    public PantryDashboard() {
        //check for null 
        this.items = new ArrayList<>();
        this.shoppingLists = new ArrayList<>();
    }

    // full constructor with associated attributes of other classes
    public PantryDashboard(User user, List<Item> items, List<ShoppingList> shoppingLists) {
        this.user = user;
        this.items = items;
        this.shoppingLists = shoppingLists;
    }

    
    private String autogenerateID() {
       //method in interface 
    }

    // method of adding items to the pantry using the item class
    public Item addItem(String itemName, String itemCategory, int itemQuantity, String itemUnit, int itemThreshold, String itemExpDate) {
        // validate inputs
        if (itemName == null || itemName.equals("")) {
            throw new IllegalArgumentException("name cant be empty");
        }
        if (itemCategory == null || itemCategory.equals("")) {
            throw new IllegalArgumentException("category cant be empty");
        }
        if (itemUnit == null || itemUnit.equals("")) {
            throw new IllegalArgumentException("unit cant be empty");
        }
        if (itemThreshold < 0) {
            throw new IllegalArgumentException("threshold cannot be negative");
        }
        if (itemQuantity < 0) {
            throw new IllegalArgumentException("quantity cannot be negative");
        }

        // some items might be of the same type but have diff ids; add their quantity
        if (items != null) { // item list should exist
            for (Item item : items) {
                if (item.getItemName().equalsIgnoreCase(itemName) &&
                    item.getItemCategory().equalsIgnoreCase(itemCategory) &&
                    item.getItemUnit().equalsIgnoreCase(itemUnit)) { 
                    // add/merge
                    item.setItemQuantity(item.getItemQuantity() + itemQuantity);
                    saveData();
                    return item;
                }
            }
        }

        // autogenerated id using methid in interface
        String itemID = autogenerateID();

        // item object created using constructor in the item class
        Item newItem = new Item(itemID, itemName, itemCategory, itemQuantity, itemUnit, itemThreshold, itemExpDate);
        items.add(newItem);
        return newItem;
    }

    // editing an item that already exists with a new one method
    public Item editItem(String itemID, String itemName, String itemCategory, int itemQuantity, String itemUnit, int itemThreshold, String itemExpDate) {
        // validate inputs using interface
        cantEmpty("Name", itemName);
        cantEmpty("Category", itemCategory);
        cantEmpty("Unit", itemUnit);
        cantBeNeg("Quantity", itemQuantity);
        cantBeNeg("Threshold", itemThreshold);

        // find the item first using ID
        Item item = findByID(items, itemID);

        // if its not found
        if (item == null) {
            System.out.println("Item not found");
            return null;
        }

        // update the item
        item.setItemName(itemName);
        item.setItemCategory(itemCategory);
        item.setItemQuantity(itemQuantity);
        item.setItemUnit(itemUnit);
        item.setItemThreshold(itemThreshold);
        item.setItemExpDate(itemExpDate);

        // return updated item
        saveData();
        return item;
    }

    // method for deleting items using id since item id are unique
    public Item deleteItem(String itemID) {
        Item item = findByID(items, itemID);
        if (item == null) {
            System.out.println("Item not found");
            return null;
        } else {
            items.remove(item);
        }
        saveData();
        return item;
    }

    // method for consuming item by using id
    public Item consumeItem(String itemID, int amount) {
        // validate input
        if (amount <= 0) {
            throw new IllegalArgumentException("amount cant be zero/negative");
        }
        // find item by id
        Item item = findByID(items, itemID);
        if (item == null) {
            System.out.println("Item not found");
            return null;
        }
        //if the quanityt in the pantry is less than what user wants for consumptioj
        if (item.getItemQuantity() - amount < 0) {
            throw new IllegalArgumentException("you dont have enough amount for consumption");
        }
        // minus
        item.setItemQuantity(item.getItemQuantity() - amount);
        saveData();
        return item;
    }

    // method for restocking an item using id and quantity
    public Item restockItem(String itemID, int amount) { 
        // validate
        if (amount <= 0) {
            throw new IllegalArgumentException("amount cant be zero/negative");
        }
        // find item by id
        Item item = findByID(items, itemID);
        if (item == null) {
            System.out.println("Item not found");
            return null;
        }
        // add
        item.setItemQuantity(item.getItemQuantity() + amount);
        saveData();
        return item;
    }

    // method for finding low stock items using item class methods
    public List<Item> FindLowStock() { // keeping your name as-is
        // empty list to store items that are low in stock
        List<Item> lowstockitems = new ArrayList<>();

        // validate
        if (items == null || items.isEmpty()) {
            System.out.print("no items in pantry");
            return lowstockitems;
        }
        // loop through items and add low stock items to the list
        for (Item item : items) {
            if (item.isLowStock()) { 
                lowstockitems.add(item);
            }
        }
        
        if (lowstockitems.isEmpty()) {
            System.out.print("no items are low in stock");
        } else {
            System.out.print("number of low in stock items found:" + lowstockitems.size());
        }
        saveData();
        return lowstockitems;
    }

    // method for finding items that are about to expire
    public List<Item> FindAboutToExpire(String currentDate) { 
        // empty list to store items that are about to expire
        List<Item> itemsabouttoexp = new ArrayList<>();

        // validate
        if (items == null || items.isEmpty()) {
            System.out.print("no items in pantry");
            return itemsabouttoexp;
        }
        // loop through items and add those about to expire
        for (Item item : items) {
            if (item.isAboutToExpire(currentDate)) {
                itemsabouttoexp.add(item);
            }
        }
        
        if (itemsabouttoexp.isEmpty()) {
            System.out.print("no items are about to expire");
        } else {
            System.out.print("number of items that are about to expire found:" + itemsabouttoexp.size());
        }
        return itemsabouttoexp;
    }

    // method to search items by keyword (name or category)
    public List<Item> search(String userinput) {
        // empty list to store items we found
        List<Item> itemsfound = new ArrayList<>();

        // validate
        if (userinput == null || userinput.equals("")) {
            System.out.print("user input cant be empty");
            return itemsfound; // FIX: was returning lowstockitems by mistake
        }
        if (items == null || items.isEmpty()) {
            System.out.print("no items in pantry");
            return itemsfound;
        }
      
        String i = userinput.toLowerCase(); //to compare einput in the if satatement 

        //loop through the list and check if userinput matches
        for (Item item : items) { 
          
            if (item.getItemName() != null && item.getItemName().toLowerCase().contains(i) || item.getItemCategory() != null && item.getItemCategory().toLowerCase().contains(i)) {
                itemsfound.add(item);
            }
        }

        if (itemsfound.isEmpty()) {
            System.out.print("no items are found");
        } else {
            System.out.print("number of items that are found:" + itemsfound.size());
        }
        return itemsfound;
    }

    //method to create the shopping list using shopping list class and only from items that are low in stock
    public ShoppingList createShoppinglist(int listId, String dateCreated) {
        //create a new list from shopping list class
        ShoppingList list = new ShoppingList(user, listId, dateCreated);

        //get all the low in stock items
        List<Item> lowstockitems = FindLowStock(); 

        //loop through items in the low in stock list
        for (Item item : lowstockitems) {
            //how much more should the user buy to reach their desired threshold of items
            int lowstockitemsneeded = item.getItemThreshold() - item.getItemQuantity();
            //check if we already have enough items or not in the pantry
            if (lowstockitemsneeded > 0) {
                //add item with the specific amount and unit to the list from the shopping class method
                try {
                    list.addItem(item, lowstockitemsneeded, item.getItemUnit());
                } catch (IllegalStateException e) {
                    System.out.println("couldnt add " + item.getItemName() + " " + e);
                }
            }
        }
        return list;
    }

  //data handeling methods:

  //loading data method
  //the method makes the dashboard remember everything even after the prohram restarts
  public void loadData(){
    //check if user exists 
    if(user==null||user.getID().equals("")){
      System.out.print("no user cant load data");
      return;
    }
    //asking backend for the user object info
    try {
      //dashboard method scans the file and returns that specific users row 
        String[][] rows = DashboardBackend.readTableDataFromFile(itemsFile.toString(), user.getID());
        if (rows == null) {
          //clear the item list so we dont gwt duplicates and if no items then create the lsit 
            if (items == null) {
            items = new ArrayList<>();
        } else {
            items.clear();
        }
          //go through each item and create an item object and rebulid the item list
          for (String[] value: rows) {
            String id = value[0];
            String name = value[1];
            String category = value[2];
            int quantity = Integer.parseInt(value[3]); //in the file its a string so convert it to int
            String unit = value[4];
            int threshold = Integer.parseInt(value[5]); //in the file its a string so convert it to int
            String expDate = value[6];
            //create item object
            Item item = new Item(id, name, category, quantity, unit, threshold, expDate);
            items.add(item);
        }
        //confirming the data laoded 
        System.out.println("items loaded for "+ user.getName() + " number of items: "+items.size()); 
  }catch(Exception e){
      System.out.print("file not found");
      items = new ArrayList<>();//new list if the file isnt foudn 
    }
}
  //method to save data 
  public void saveData(){
   //check if user exists 
    if(user==null||user.getID().equals("")){
      System.out.print("no user cant load data");
      return;
    }
    try{
    //opening file for overwriting 
      PrintWriter fout=new PrintWriter(itemsFile.toString());
      //looping through every item in the list and writing it into the file
      for(Item item:items){
        fout.println(user.getItemID()+","+item.getID()+","+item.getItemID()+","+item.getItemName()+","+item.getItemCategory()+","+item.getItemQuantity()+","+item.getItemUnit()+","
                       +item.getItemThreshold()+","+item.getItemExpDate());
      }
      fout.close(); //close file
      System.out.print("items saved for"+user.getName() + " number of items: "+items.size()); 
      }catch(Exception e){
      System.out.print("cannot save data");
    }
    }
    //method for updating list we just need to reload the items from the file to refresh the pantry
    public void updateList(){
      loadData();
    }

    //printing the low in stock items to the console 
    public void displayLowStock(){
      List<Item> lowstockitems = FindLowStock();  //get the low stock items 
      
      //validate that there are low stock items
      if(lowstockitems==null||lowstockitems.isEmpty()){
        System.out.print("no low in stock items");
        return;
      }else {
        System.out.print("low in stock items: "+ lowstockitems);
      }
      //loop through list and pritn 
      for(Item item:lowstockitems){
        System.out.print("["+ item.getItemName()+ ","+ item.getItemQuantity()+ ","+ item.getItemUnit()+ ","+ item.getItemThreshold()+ "]");
      }
    }

    //printing about to expire items to console
    public void displayAboutToExpire(String currentDate){
      List<Item> itemsabouttoexp = FindAboutToExpire(currentDate); //get the about to expire items 
      
      //validate that there are expired items
      if(itemsabouttoexp==null||itemsabouttoexp.isEmpty()){
        System.out.print("no items are about to expire");
        return;
      }else {
        System.out.print("items that are about to expire: "+ itemsabouttoexp);
      }
      //loop through list and pritn 
      for(Item item:itemsabouttoexp){
        System.out.print("["+ item.getItemName()+ "," +item.getItemExpDate()+","+ item.getItemQuantity()+ ","+ item.getItemUnit()+ ","+"]");
      }
    }

    // method of adding items to the pantry using the item class
    public Item addItem(String itemName, String itemCategory, int itemQuantity, String itemUnit, int itemThreshold, String itemExpDate) {
        // validate inputs
        if (itemName == null || itemName.equals("")) {
            throw new IllegalArgumentException("name cant be empty");
        }
        if (itemCategory == null || itemCategory.equals("")) {
            throw new IllegalArgumentException("category cant be empty");
        }
        if (itemUnit == null || itemUnit.equals("")) {
            throw new IllegalArgumentException("unit cant be empty");
        }
        if (itemThreshold < 0) {
            throw new IllegalArgumentException("threshold cannot be negative");
        }
        if (itemQuantity < 0) {
            throw new IllegalArgumentException("quantity cannot be negative");
        }

        // some items might be of the same type but have diff ids; add their quantity
        if (items != null) { // item list should exist
            for (Item item : items) {
                if (item.getItemName().equalsIgnoreCase(itemName) &&
                    item.getItemCategory().equalsIgnoreCase(itemCategory) &&
                    item.getItemUnit().equalsIgnoreCase(itemUnit)) { 
                    // add/merge
                    item.setItemQuantity(item.getItemQuantity() + itemQuantity);
                    saveData();
                    return item;
                }
            }
        }

        // autogenerated id
        String itemID = autogenerateID();

        // item object created using constructor in the item class
        Item newItem = new Item(itemID, itemName, itemCategory, itemQuantity, itemUnit, itemThreshold, itemExpDate);
        items.add(newItem);
        saveData();
        return newItem;
    }

    // editing an item that already exists with a new one method
    public Item editItem(String itemID, String itemName, String itemCategory, int itemQuantity, String itemUnit, int itemThreshold, String itemExpDate) {
        // validate inputs using interface
        cantEmpty("Name", itemName);
        cantEmpty("Category", itemCategory);
        cantEmpty("Unit", itemUnit);
        cantBeNeg("Quantity", itemQuantity);
        cantBeNeg("Threshold", itemThreshold);

        // find the item first using ID
        Item item = findByID(items, itemID);

        // if its not found
        if (item == null) {
            System.out.println("Item not found");
            return null;
        }

        // update the item
        item.setItemName(itemName);
        item.setItemCategory(itemCategory);
        item.setItemQuantity(itemQuantity);
        item.setItemUnit(itemUnit);
        item.setItemThreshold(itemThreshold);
        item.setItemExpDate(itemExpDate);

        // return updated item
        saveData();
        return item;
    }

    // method for deleting items using id since item id are unique
    public Item deleteItem(String itemID) {
        Item item = findByID(items, itemID);
        if (item == null) {
            System.out.println("Item not found");
            return null;
        } else {
            items.remove(item);
        }
        saveData();
        return item;
    }

    // method for consuming item by using id
    public Item consumeItem(String itemID, int amount) {
        // validate input
        if (amount <= 0) {
            throw new IllegalArgumentException("amount cant be zero/negative");
        }
        // find item by id
        Item item = findByID(items, itemID);
        if (item == null) {
            System.out.println("Item not found");
            return null;
        }
        //if the quanityt in the pantry is less than what user wants for consumptioj
        if (item.getItemQuantity() - amount < 0) {
            throw new IllegalArgumentException("you dont have enough amount for consumption");
        }
        // minus
        item.setItemQuantity(item.getItemQuantity() - amount);
        saveData();
        return item;
    }

    // method for restocking an item using id and quantity
    public Item restockItem(String itemID, int amount) { 
        // validate
        if (amount <= 0) {
            throw new IllegalArgumentException("amount cant be zero/negative");
        }
        // find item by id
        Item item = findByID(items, itemID);
        if (item == null) {
            System.out.println("Item not found");
            return null;
        }
        // add
        item.setItemQuantity(item.getItemQuantity() + amount);
        saveData();
        return item;
    }

    // method for finding low stock items using item class methods
    public List<Item> FindLowStock() { // keeping your name as-is
        // empty list to store items that are low in stock
        List<Item> lowstockitems = new ArrayList<>();

        // validate
        if (items == null || items.isEmpty()) {
            System.out.print("no items in pantry");
            return lowstockitems;
        }
        // loop through items and add low stock items to the list
        for (Item item : items) {
            if (item.isLowStock()) { 
                lowstockitems.add(item);
            }
        }
        
        if (lowstockitems.isEmpty()) {
            System.out.print("no items are low in stock");
        } else {
            System.out.print("number of low in stock items found:" + lowstockitems.size());
        }
       
        return lowstockitems;
    }

    // method for finding items that are about to expire
    public List<Item> FindAboutToExpire(String currentDate) { 
        // empty list to store items that are about to expire
        List<Item> itemsabouttoexp = new ArrayList<>();

        // validate
        if (items == null || items.isEmpty()) {
            System.out.print("no items in pantry");
            return itemsabouttoexp;
        }
        // loop through items and add those about to expire
        for (Item item : items) {
            if (item.isAboutToExpire(currentDate)) {
                itemsabouttoexp.add(item);
            }
        }
        
        if (itemsabouttoexp.isEmpty()) {
            System.out.print("no items are about to expire");
        } else {
            System.out.print("number of items that are about to expire found:" + itemsabouttoexp.size());
        }
        return itemsabouttoexp;
    }

    // method to search items by keyword (name or category)
    public List<Item> search(String userinput) {
        // empty list to store items we found
        List<Item> itemsfound = new ArrayList<>();

        // validate
        if (userinput == null || userinput.equals("")) {
            System.out.print("user input cant be empty");
            return itemsfound; // FIX: was returning lowstockitems by mistake
        }
        if (items == null || items.isEmpty()) {
            System.out.print("no items in pantry");
            return itemsfound;
        }

        String i = userinput.toLowerCase();

        //loop through the list and check if userinput matches
        for (Item item : items) { 
          
            if (item.getItemName() != null && item.getItemName().toLowerCase().contains(i) || item.getItemCategory() != null && item.getItemCategory().toLowerCase().contains(i)) {
                itemsfound.add(item);
            }
        }

        if (itemsfound.isEmpty()) {
            System.out.print("no items are found");
        } else {
            System.out.print("number of items that are found:" + itemsfound.size());
        }
        return itemsfound;
    }

    //method to create the shopping list using shopping list class and only from items that are low in stock
    public ShoppingList createShoppinglist(int listId, String dateCreated) {
        //create a new list from shopping list class
        ShoppingList list = new ShoppingList(user, listId, dateCreated);

        //get all the low in stock items
        List<Item> lowstockitems = FindLowStock(); 

        //loop through items in the low in stock list
        for (Item item : lowstockitems) {
            //how much more should the user buy to reach their desired threshold of items
            int lowstockitemsneeded = item.getItemThreshold() - item.getItemQuantity();
            //check if we already have enough items or not in the pantry
            if (lowstockitemsneeded > 0) {
                //add item with the specific amount and unit to the list from the shopping class method
                try {
                    list.addItem(item, lowstockitemsneeded, item.getItemUnit());
                } catch (IllegalStateException e) {
                    System.out.println("couldnt add " + item.getItemName() + " " + e);
                }
            }
        }
        return list;
    }

  //data handeling methods:

  //loading data method
  //the method makes the dashboard remember everything even after the prohram restarts
  public void loadData(){
    //check if user exists 
    if(user==null||user.getID().equals("")){
      System.out.print("no user cant load data");
      return;
    }
    //asking backend for the user object info
    try {
      //dashboard method scans the file and returns that specific users row 
        String[][] rows = DashboardBackend.readTableDataFromFile(itemsFile.toString(), user.getID());
        if (rows == null) {
          //clear the item list so we dont gwt duplicates and if no items then create the lsit 
            if (items == null) {
            items = new ArrayList<>();
        } else {
            items.clear();
        }
          //go through each item and create an item object and rebulid the item list
      for (String[] value: rows) {
        String id = value[0];
        String name = value[1];
        String category = value[2];
        int quantity = Integer.parseInt(value[3]); //in the file its a string so convert it to int
        String unit = value[4];
        int threshold = Integer.parseInt(value[5]); //in the file its a string so convert it to int
        String expDate = value[6];
            //create item object
        Item item = new Item(id, name, category, quantity, unit, threshold, expDate);
         items.add(item);
        }
        //confirming the data laoded 
        System.out.println("items loaded for: "+ user.getName() + " number of items: "+items.size()); 
  }catch(Exception e){
      System.out.print("file not found");
      items = new ArrayList<>();//new list if the file isnt foudn 
    }
}
  //method to save data 
  public void saveData(){
   //check if user exists 
    if(user==null||user.getItemID().equals("")){
      System.out.print("no user cant load data");
      return;
    }
    try{
    //opening file for overwriting 
      PrintWriter fout=new PrintWriter(itemsFile.toString());
      //looping through every item in the list and writing it into the file
      for(Item item:items){
        fout.println("["+user.getItemID()+","+item.getItemID()+","+item.getItemID()+","+item.getItemName()+","+item.getItemCategory()+","+item.getItemQuantity()+","+item.getItemUnit()+","
                       +item.getItemThreshold()+","+item.getItemExpDate()+"]");
      }
      fout.close(); //close file
      System.out.print("items saved for"+user.getName() + " number of items: "+items.size()); 
      }catch(Exception e){
      System.out.print("cannot save data");
    }
    }
    //method for updating list we just need to reload the items from the file to refresh the pantry
    public void updateList(){
      loadData();
    }

    //printing the low in stock items to the console 
    public void displayLowStock(){
      List<Item> lowstockitems = FindLowStock();  //get the low stock items 
      
      //validate that there are low stock items
      if(lowstockitems==null||lowstockitems.isEmpty()){
        System.out.print("no low in stock items");
        return;
      }else {
        System.out.print("low in stock items: "+ lowstockitems);
      }
      //loop through list and pritn 
      for(Item item:lowstockitems){
        System.out.print("["+ item.getItemName()+ ","+ item.getItemQuantity()+ ","+ item.getItemUnit()+ ","+ item.getItemThreshold()+ "]");
      }
    }

    //printing about to expire items to console
    public void displayAboutToExpire(String currentDate){
      List<Item> itemsabouttoexp = FindAboutToExpire(currentDate); //get the about to expire items 
      
      //validate that there are expired items
      if(itemsabouttoexp==null||itemsabouttoexp.isEmpty()){
        System.out.print("no items are about to expire");
        return;
      }else {
        System.out.print("items that are about to expire: "+ itemsabouttoexp);
      }
      //loop through list and pritn 
      for(Item item:itemsabouttoexp){
        System.out.print("["+ item.getItemName()+ "," +item.getItemExpDate()+","+ item.getItemQuantity()+ ","+ item.getItemUnit()+ ","+"]");
      }
    }
    
    
public class PantryDashboard {
}
